<?xml version="1.0" encoding="utf-8"?><Database Name="AbogadosEasySoft" Class="AbogadosDataModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NULLPTR\SQLEXPRESS;Initial Catalog=AbogadosEasySoft;Integrated Security=True" SettingsObjectName="AbogadosEasySoft.Properties.Settings" SettingsPropertyName="AbogadosEasySoftConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="privilege" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="cliente">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="img" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cedula" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="pasaporte" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="segundo_nombre" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="segundo_apellido" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="provincia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="municipio" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="estado_civil" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="empleado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion_empleo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="servicio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="costo_servicio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="abono" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="fiscalia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="procurador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="notas" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_actual" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>