#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbogadosEasySoft.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AbogadosEasySoft")]
	public partial class AbogadosDataModelsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    #endregion
		
		public AbogadosDataModelsDataContext() : 
				base(global::AbogadosEasySoft.Properties.Settings.Default.AbogadosEasySoftConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AbogadosDataModelsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbogadosDataModelsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbogadosDataModelsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbogadosDataModelsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _privilege;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnprivilegeChanging(string value);
    partial void OnprivilegeChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privilege", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string privilege
		{
			get
			{
				return this._privilege;
			}
			set
			{
				if ((this._privilege != value))
				{
					this.OnprivilegeChanging(value);
					this.SendPropertyChanging();
					this._privilege = value;
					this.SendPropertyChanged("privilege");
					this.OnprivilegeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Data.Linq.Binary _img;
		
		private string _cedula;
		
		private string _pasaporte;
		
		private string _nombre;
		
		private string _segundo_nombre;
		
		private string _apellido;
		
		private string _segundo_apellido;
		
		private string _email;
		
		private string _contacto;
		
		private string _direccion;
		
		private string _provincia;
		
		private string _municipio;
		
		private string _telefono;
		
		private string _celular;
		
		private string _estado_civil;
		
		private string _empleado;
		
		private string _direccion_empleo;
		
		private string _servicio;
		
		private decimal _costo_servicio;
		
		private decimal _abono;
		
		private string _fiscalia;
		
		private string _procurador;
		
		private string _notas;
		
		private System.DateTime _fecha_actual;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnimgChanging(System.Data.Linq.Binary value);
    partial void OnimgChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnpasaporteChanging(string value);
    partial void OnpasaporteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onsegundo_nombreChanging(string value);
    partial void Onsegundo_nombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void Onsegundo_apellidoChanging(string value);
    partial void Onsegundo_apellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncontactoChanging(string value);
    partial void OncontactoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnprovinciaChanging(string value);
    partial void OnprovinciaChanged();
    partial void OnmunicipioChanging(string value);
    partial void OnmunicipioChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void Onestado_civilChanging(string value);
    partial void Onestado_civilChanged();
    partial void OnempleadoChanging(string value);
    partial void OnempleadoChanged();
    partial void Ondireccion_empleoChanging(string value);
    partial void Ondireccion_empleoChanged();
    partial void OnservicioChanging(string value);
    partial void OnservicioChanged();
    partial void Oncosto_servicioChanging(decimal value);
    partial void Oncosto_servicioChanged();
    partial void OnabonoChanging(decimal value);
    partial void OnabonoChanged();
    partial void OnfiscaliaChanging(string value);
    partial void OnfiscaliaChanged();
    partial void OnprocuradorChanging(string value);
    partial void OnprocuradorChanged();
    partial void OnnotasChanging(string value);
    partial void OnnotasChanged();
    partial void Onfecha_actualChanging(System.DateTime value);
    partial void Onfecha_actualChanged();
    #endregion
		
		public cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="NChar(11)")]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasaporte", DbType="NChar(20)")]
		public string pasaporte
		{
			get
			{
				return this._pasaporte;
			}
			set
			{
				if ((this._pasaporte != value))
				{
					this.OnpasaporteChanging(value);
					this.SendPropertyChanging();
					this._pasaporte = value;
					this.SendPropertyChanged("pasaporte");
					this.OnpasaporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_nombre", DbType="NVarChar(15)")]
		public string segundo_nombre
		{
			get
			{
				return this._segundo_nombre;
			}
			set
			{
				if ((this._segundo_nombre != value))
				{
					this.Onsegundo_nombreChanging(value);
					this.SendPropertyChanging();
					this._segundo_nombre = value;
					this.SendPropertyChanged("segundo_nombre");
					this.Onsegundo_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="NVarChar(15)")]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this.Onsegundo_apellidoChanging(value);
					this.SendPropertyChanging();
					this._segundo_apellido = value;
					this.SendPropertyChanged("segundo_apellido");
					this.Onsegundo_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacto", DbType="VarChar(50)")]
		public string contacto
		{
			get
			{
				return this._contacto;
			}
			set
			{
				if ((this._contacto != value))
				{
					this.OncontactoChanging(value);
					this.SendPropertyChanging();
					this._contacto = value;
					this.SendPropertyChanged("contacto");
					this.OncontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this.OnmunicipioChanging(value);
					this.SendPropertyChanging();
					this._municipio = value;
					this.SendPropertyChanged("municipio");
					this.OnmunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NChar(10)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="NChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_civil", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string estado_civil
		{
			get
			{
				return this._estado_civil;
			}
			set
			{
				if ((this._estado_civil != value))
				{
					this.Onestado_civilChanging(value);
					this.SendPropertyChanging();
					this._estado_civil = value;
					this.SendPropertyChanged("estado_civil");
					this.Onestado_civilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empleado", DbType="VarChar(50)")]
		public string empleado
		{
			get
			{
				return this._empleado;
			}
			set
			{
				if ((this._empleado != value))
				{
					this.OnempleadoChanging(value);
					this.SendPropertyChanging();
					this._empleado = value;
					this.SendPropertyChanged("empleado");
					this.OnempleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_empleo", DbType="VarChar(50)")]
		public string direccion_empleo
		{
			get
			{
				return this._direccion_empleo;
			}
			set
			{
				if ((this._direccion_empleo != value))
				{
					this.Ondireccion_empleoChanging(value);
					this.SendPropertyChanging();
					this._direccion_empleo = value;
					this.SendPropertyChanged("direccion_empleo");
					this.Ondireccion_empleoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string servicio
		{
			get
			{
				return this._servicio;
			}
			set
			{
				if ((this._servicio != value))
				{
					this.OnservicioChanging(value);
					this.SendPropertyChanging();
					this._servicio = value;
					this.SendPropertyChanged("servicio");
					this.OnservicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_servicio", DbType="Money NOT NULL")]
		public decimal costo_servicio
		{
			get
			{
				return this._costo_servicio;
			}
			set
			{
				if ((this._costo_servicio != value))
				{
					this.Oncosto_servicioChanging(value);
					this.SendPropertyChanging();
					this._costo_servicio = value;
					this.SendPropertyChanged("costo_servicio");
					this.Oncosto_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abono", DbType="Money NOT NULL")]
		public decimal abono
		{
			get
			{
				return this._abono;
			}
			set
			{
				if ((this._abono != value))
				{
					this.OnabonoChanging(value);
					this.SendPropertyChanging();
					this._abono = value;
					this.SendPropertyChanged("abono");
					this.OnabonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiscalia", DbType="VarChar(50)")]
		public string fiscalia
		{
			get
			{
				return this._fiscalia;
			}
			set
			{
				if ((this._fiscalia != value))
				{
					this.OnfiscaliaChanging(value);
					this.SendPropertyChanging();
					this._fiscalia = value;
					this.SendPropertyChanged("fiscalia");
					this.OnfiscaliaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procurador", DbType="VarChar(50)")]
		public string procurador
		{
			get
			{
				return this._procurador;
			}
			set
			{
				if ((this._procurador != value))
				{
					this.OnprocuradorChanging(value);
					this.SendPropertyChanging();
					this._procurador = value;
					this.SendPropertyChanged("procurador");
					this.OnprocuradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notas", DbType="VarChar(50)")]
		public string notas
		{
			get
			{
				return this._notas;
			}
			set
			{
				if ((this._notas != value))
				{
					this.OnnotasChanging(value);
					this.SendPropertyChanging();
					this._notas = value;
					this.SendPropertyChanged("notas");
					this.OnnotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actual", DbType="Date NOT NULL")]
		public System.DateTime fecha_actual
		{
			get
			{
				return this._fecha_actual;
			}
			set
			{
				if ((this._fecha_actual != value))
				{
					this.Onfecha_actualChanging(value);
					this.SendPropertyChanging();
					this._fecha_actual = value;
					this.SendPropertyChanged("fecha_actual");
					this.Onfecha_actualChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
